FROM node:18-alpine 

# Create app directory
WORKDIR /user/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install --production

# copy the rest of the app
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Serve the app
CMD ["npm", "start"]



